
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FAMS_Data
{

using System;
    using System.Collections.Generic;
    
public partial class Approval
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Approval()
    {

        this.ApprovalDetail = new HashSet<ApprovalDetail>();

        this.ApprovalDocument = new HashSet<ApprovalDocument>();

    }


    public long Id { get; set; }

    public long ReleaseMatrixId { get; set; }

    public string ReferenceNo { get; set; }

    public string ReferenceNo1 { get; set; }

    public string ReferenceNo2 { get; set; }

    public string Category { get; set; }

    public string Mode { get; set; }

    public string Info1 { get; set; }

    public string Info2 { get; set; }

    public string Remarks { get; set; }

    public string Status { get; set; }

    public string Active { get; set; }

    public string LastApprovalBy { get; set; }

    public Nullable<System.DateTime> LastApprovalDate { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string CreatedBy { get; set; }



    public virtual ReleaseMatrix ReleaseMatrix { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ApprovalDetail> ApprovalDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ApprovalDocument> ApprovalDocument { get; set; }

}

}
