
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FAMS_Data
{

using System;
    using System.Collections.Generic;
    
public partial class ApprovalDetail
{

    public long Id { get; set; }

    public long ApprovalId { get; set; }

    public string ApprovalAs { get; set; }

    public string Username { get; set; }

    public Nullable<int> Level { get; set; }

    public string Status { get; set; }

    public string Active { get; set; }

    public string LastApproval { get; set; }

    public Nullable<System.DateTime> ApprovalDate { get; set; }

    public string ApprovalBy { get; set; }

    public string Info1 { get; set; }

    public string Info2 { get; set; }

    public string Remarks { get; set; }



    public virtual Approval Approval { get; set; }

}

}
