

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FAMS_Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class FAMSEntities : DbContext
{
    public FAMSEntities()
        : base("name=FAMSEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<APISetting> APISetting { get; set; }

    public virtual DbSet<Approval> Approval { get; set; }

    public virtual DbSet<ApprovalDetail> ApprovalDetail { get; set; }

    public virtual DbSet<ApprovalDocument> ApprovalDocument { get; set; }

    public virtual DbSet<Asset> Asset { get; set; }

    public virtual DbSet<CertificateType> CertificateType { get; set; }

    public virtual DbSet<Changelog> Changelog { get; set; }

    public virtual DbSet<ChangelogDetail> ChangelogDetail { get; set; }

    public virtual DbSet<Department> Department { get; set; }

    public virtual DbSet<Group> Group { get; set; }

    public virtual DbSet<GroupMenu> GroupMenu { get; set; }

    public virtual DbSet<Localization> Localization { get; set; }

    public virtual DbSet<LocationSAP> LocationSAP { get; set; }

    public virtual DbSet<Lookup> Lookup { get; set; }

    public virtual DbSet<Menu> Menu { get; set; }

    public virtual DbSet<Module> Module { get; set; }

    public virtual DbSet<ModuleDocument> ModuleDocument { get; set; }

    public virtual DbSet<ModuleTask> ModuleTask { get; set; }

    public virtual DbSet<ModuleTaskDetail> ModuleTaskDetail { get; set; }

    public virtual DbSet<ModuleType> ModuleType { get; set; }

    public virtual DbSet<ModuleTypeDetail> ModuleTypeDetail { get; set; }

    public virtual DbSet<NotificationLog> NotificationLog { get; set; }

    public virtual DbSet<ReleaseMatrix> ReleaseMatrix { get; set; }

    public virtual DbSet<ReleaseMatrixDetail> ReleaseMatrixDetail { get; set; }

    public virtual DbSet<Request> Request { get; set; }

    public virtual DbSet<RequestAttachment> RequestAttachment { get; set; }

    public virtual DbSet<RequestDetail> RequestDetail { get; set; }

    public virtual DbSet<RequestLog> RequestLog { get; set; }

    public virtual DbSet<RequestLogDetail> RequestLogDetail { get; set; }

    public virtual DbSet<RequestTask> RequestTask { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<RunningNumber> RunningNumber { get; set; }

    public virtual DbSet<RunningNumberDate> RunningNumberDate { get; set; }

    public virtual DbSet<RunningNumberMonth> RunningNumberMonth { get; set; }

    public virtual DbSet<RunningNumberYear> RunningNumberYear { get; set; }

    public virtual DbSet<Setting> Setting { get; set; }

    public virtual DbSet<UoM> UoM { get; set; }

    public virtual DbSet<User> User { get; set; }

    public virtual DbSet<UserCompany> UserCompany { get; set; }

    public virtual DbSet<UserDepartment> UserDepartment { get; set; }

    public virtual DbSet<UserGroup> UserGroup { get; set; }

    public virtual DbSet<UserLocation> UserLocation { get; set; }

    public virtual DbSet<UserPassLog> UserPassLog { get; set; }

    public virtual DbSet<UserRole> UserRole { get; set; }

    public virtual DbSet<UserToken> UserToken { get; set; }

}

}

