
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FAMS_Data
{

using System;
    using System.Collections.Generic;
    
public partial class ModuleDocument
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ModuleDocument()
    {

        this.RequestAttachment = new HashSet<RequestAttachment>();

    }


    public long Id { get; set; }

    public long ModuleId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public string Mandatory { get; set; }

    public string PIC { get; set; }

    public Nullable<int> MaxSizeKB { get; set; }

    public string Extension { get; set; }

    public string Info { get; set; }

    public string Type { get; set; }

    public Nullable<System.DateTime> ValidFrom { get; set; }

    public Nullable<System.DateTime> ValidTo { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string EditedBy { get; set; }

    public Nullable<System.DateTime> EditedDate { get; set; }

    public string IsDeleted { get; set; }

    public string DeletedBy { get; set; }

    public Nullable<System.DateTime> DeletedDate { get; set; }



    public virtual Module Module { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RequestAttachment> RequestAttachment { get; set; }

}

}
