
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FAMS_Data
{

using System;
    using System.Collections.Generic;
    
public partial class ModuleTypeDetail
{

    public long Id { get; set; }

    public long ModuleTypeId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public string Proses { get; set; }

    public string Filling { get; set; }

    public string Tcode { get; set; }

    public string IsNeedDestination { get; set; }

    public string Info { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string EditedBy { get; set; }

    public Nullable<System.DateTime> EditedDate { get; set; }

    public string IsDeleted { get; set; }

    public string DeletedBy { get; set; }

    public Nullable<System.DateTime> DeletedDate { get; set; }



    public virtual ModuleType ModuleType { get; set; }

}

}
