
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FAMS_Data
{

using System;
    using System.Collections.Generic;
    
public partial class ReleaseMatrix
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ReleaseMatrix()
    {

        this.Approval = new HashSet<Approval>();

        this.ReleaseMatrixDetail = new HashSet<ReleaseMatrixDetail>();

    }


    public long Id { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public string Modul { get; set; }

    public string Transaction_Type { get; set; }

    public string SAPCompanyCode { get; set; }

    public string DepartmentCode { get; set; }

    public string LocationCode { get; set; }

    public string Type { get; set; }

    public string Validity { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string EditedBy { get; set; }

    public Nullable<System.DateTime> EditedDate { get; set; }

    public string IsDeleted { get; set; }

    public string DeletedBy { get; set; }

    public Nullable<System.DateTime> DeletedDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Approval> Approval { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ReleaseMatrixDetail> ReleaseMatrixDetail { get; set; }

}

}
