
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FAMS_Data
{

using System;
    using System.Collections.Generic;
    
public partial class RequestLog
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public RequestLog()
    {

        this.RequestLogDetail = new HashSet<RequestLogDetail>();

    }


    public long Id { get; set; }

    public string TransactionNo { get; set; }

    public string RefNo { get; set; }

    public string ActionRole { get; set; }

    public string Action { get; set; }

    public string Notes { get; set; }

    public string ActionBy { get; set; }

    public string ActionUsername { get; set; }

    public Nullable<System.DateTime> ActionDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RequestLogDetail> RequestLogDetail { get; set; }

}

}
